### ISSUE TITLE
qrz doesn't respond properly to profiles with incomplete data

### ISSUE THREAD

**Issue by classabbyamp** [classabbyamp/discord-qrm2#124]
Handle incomplete profile data with a `--` or similar to prevent embed errors

![image](https://user-images.githubusercontent.com/5366828/71304821-9da49980-2399-11ea-83ed-0a4e55b81a3e.png)

`?qrz vk2ooo` yields:
```
qrm2_1  | Ignoring exception in command call:
qrm2_1  | Traceback (most recent call last):
qrm2_1  |   File "/usr/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
qrm2_1  |     ret = await coro(*args, **kwargs)
qrm2_1  |   File "/app/exts/qrz.py", line 84, in _qrz_lookup
qrm2_1  |     await ctx.send(embed=embed)
qrm2_1  |   File "/usr/lib/python3.7/site-packages/discord/abc.py", line 823, in send
qrm2_1  |     data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
qrm2_1  |   File "/usr/lib/python3.7/site-packages/discord/http.py", line 222, in request
qrm2_1  |     raise HTTPException(r, data)
qrm2_1  | discord.errors.HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
qrm2_1  | In embed.fields.1.value: This field is required
qrm2_1  | 
qrm2_1  | The above exception was the direct cause of the following exception:
qrm2_1  | 
qrm2_1  | Traceback (most recent call last):
qrm2_1  |   File "/usr/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
qrm2_1  |     await ctx.command.invoke(ctx)
qrm2_1  |   File "/usr/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
qrm2_1  |     await injected(*ctx.args, **ctx.kwargs)
qrm2_1  |   File "/usr/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
qrm2_1  |     raise CommandInvokeError(exc) from exc
qrm2_1  | discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
qrm2_1  | In embed.fields.1.value: This field is required
```

**Comment by classabbyamp** [comment]
```
'Name': None
'Country': 'Australia'
'Address': '\n '
'Grid Square': 'QF56od'
'County': None
'CQ Zone': None
'ITU Zone': None
'IOTA Designator': None
'Expires': None
'Aliases': None
'Previous Callsign': None
'License Class': None
'eQSL?': 'No'
'Paper QSL?': 'No'
'LotW?': 'No'
'QSL Info': None
'Born': None
```
The issue is with the address, it's `\n` not `None`
